apiVersion: v1
kind: Service
metadata:
  name: gogo-preproduction
spec:
  selector:
    app: gogo-preproduction
  type: LoadBalancer

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000